language: go

sudo: required

services:
  - docker

go:
  - 1.5

before_install:
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine

install:
  - go get -v -d

before_script:
  - docker version
  - make binary-linux-amd64
  - chmod +x bin/linux/amd64/local-persist
  - sudo ./bin/linux/amd64/local-persist &

script:
  - ./scripts/integration.sh
  - make test

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/305f56dee3c41da57807
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
