language: go

sudo: required

services:
  - docker

go:
  - 1.5

install:
  - go get -v -d

before_script:
  - make binary-linux-amd64
  - chmod +x bin/linux/amd64/local-persist
  - sudo ./bin/linux/amd64/local-persist &

script:
  - ./scripts/integration.sh
  - make test
