version: '2'

services:
  one:
    image: alpine
    working_dir: /one/
    command: sleep 6000
    volumes:
      - data:/one/

  two:
    image: alpine
    working_dir: /two/
    command: sleep 6000
    volumes:
      - data:/two/

volumes:
  data:
    driver: local-persist
    driver_opts:
      mountpoint: /docker-data/images
